CREATE DATABASE student_portal;
USE student_portal;
CREATE TABLE users (
id INT AUTO_INCREMENT PRIMARY KEY,
full_name VARCHAR(100),
email VARCHAR(100),
password VARCHAR(150),
course VARCHAR(50),
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE result(
id INT AUTO_INCREMENT PRIMARY KEY,
student_email VARCHAR(100),
course VARCHAR(50),
score INT,
total INT,
exam_date DATETIME DEFAULT CURRENT_TIMESTAMP);